In [1]:
# Input info
# se_f = "/data/Mito_Trace/output/pipeline/TcellDupi_may17_2021/MTblacklist/data/merged/MT/cellr_True/numread_200/filters/minC10_minR50_topN0_hetT0.001_hetC10_hetCount5_bq20/mgatk/vireoIn/clones/variants_init/knn/kparam_3/concat/gff_hg38_1_2/annotation_clones/SE.rds"
# minCell = 1
# outdir = "/data/Mito_Trace/output/pipeline/TcellDupi_may17_2021/MTblacklist/data/merged/MT/cellr_True/numread_200/filters/minC10_minR50_topN0_hetT0.001_hetC10_hetCount5_bq20/mgatk/vireoIn/clones/variants_init/knn/kparam_3/concat/gff_hg38_1_2/annotation_clones/clone_counts/minCellConds_1" 
# sample_names = "pre,post"

se_f = "/data/Mito_Trace/output/pipeline/v02/CHIP_b1/MTBlacklist_A2/data/merged/MT/cellr_True/numread_200/filters/minC10_minR50_topN0_hetT0.001_hetC10_hetCount5_bq20/mgatk/vireoIn/clones/variants_mgatkdonor/knn/kparam_30/gff_A2_black/annotation_clones/SE.rds"
outdir = "/data/Mito_Trace/output/pipeline/v02/CHIP_b1/MTBlacklist_A2/data/merged/MT/cellr_True/numread_200/filters/minC10_minR50_topN0_hetT0.001_hetC10_hetCount5_bq20/mgatk/vireoIn/clones/variants_mgatkdonor/knn/kparam_30/gff_A2_black/annotation_clones/clone_counts/minCellConds_1"
sample_names = "Control,Flt3l,Input" 
minCell = 1 


# Parallel processing
cores = 4

# R utils script
utils_script <- "/data/Mito_Trace/R_scripts/seurat_utils.R"

In [2]:
source(utils_script)
#source("/data/Mito_Trace/R_scripts/plot_de_over_all.R")

Attaching SeuratObject


Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [3]:
dir.create(outdir, showWarnings = TRUE)

Warning message in dir.create(outdir, showWarnings = TRUE):
“'/data/Mito_Trace/output/pipeline/v02/CHIP_b1/MTBlacklist_A2/data/merged/MT/cellr_True/numread_200/filters/minC10_minR50_topN0_hetT0.001_hetC10_hetCount5_bq20/mgatk/vireoIn/clones/variants_mgatkdonor/knn/kparam_30/gff_A2_black/annotation_clones/clone_counts/minCellConds_1' already exists”

In [4]:
sample_names <- unlist(strsplit(sample_names, ",")[[1]])
sample_names

[1] "Control" "Flt3l"   "Input"

In [5]:
library(GenomicRanges)
library(Seurat)
library(Signac)
library(GenomeInfoDb)
library(EnsDb.Hsapiens.v75)
library(ggplot2)
library(patchwork)
set.seed(1234)
library(data.table)
library(magrittr)
library(cowplot)
library(metap)
library("RColorBrewer")
library(dplyr)
library(future)
plan()

plan("multiprocess", workers = cores)
#options(future.globals.maxSize = 50000 * 1024^2) # for 50 Gb RAM
options(future.globals.maxSize = 8000 * 1024^2)

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:dplyr’:

    first, rename


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice


Loading required package: GenomeInfoDb

Loading required package: ensembldb

Loading required package: GenomicFeatures

Loading required package: AnnotationDbi

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘AnnotationDbi’


The following object is masked from ‘package:dplyr’:

    select


Loading required package: AnnotationFilter


Attaching package: 'ensembldb'


The following object is masked from 'package:dplyr':

    filter


The following object is masked from 'package:stats':

    filter



Attaching package: 'data.table'


The following object is masked from 'package:GenomicRanges':

    shift


The following object is masked from 'package:IRanges':

    shift


The following objects are masked from 'package:S4Vectors':

    first, second


The following objects are masked from 'package:dplyr':

    between, first, last



Attaching package: 'magrittr'


The following object is masked from 'package:AnnotationFilter':

    not



Attaching package: 'cowplot'


The following object is masked from 'package:patchwork':

    align_plots



Attaching package: 'future'


The following object is masked from 'package:AnnotationFilter':

    value


The following object is masked from 'package:GenomicRanges':

    values


The following object is masked from 'package:S4Vectors':

    values

sequential:
- args: function (..., envir = parent.frame())
- tweaked: FALSE
- call: NULL

Warning message:
"Strategy 'multiprocess' is deprecated in future (>= 1.20.0). Instead, explicitly specify either 'multisession' or 'multicore'. In the current R session, 'multiprocess' equals 'multicore'."

In [6]:
library(dplyr)

In [7]:
se <- readRDS(se_f)#file.path(indir, paste0("allSamples.integrated.rds")))
se

An object of class Seurat
221404 features across 18672 samples within 2 assays
Active assay: RNA (19039 features, 0 variable features)
 1 other assay present: ATAC
 2 dimensional reductions calculated: integrated_lsi, umap

# Get clones with mininum  cells in each condition and run DE pre and post

In [8]:
source(utils_script)
tmp = get.clone.sizes(se)
counts.norm=tmp[["counts.norm"]]
clone.sizes = tmp[["clone.size"]]
head(clone.sizes)

`summarise()` has grouped output by 'condition', 'donor', 'lineage'. You can override using the
`.groups` argument.
Warning message in xtfrm.data.frame(x):
"cannot xtfrm data frames"
`summarise()` has grouped output by 'donor'. You can override using the `.groups` argument.

  donor lineage norm.total total name cdf.norm  cdf  index
1 0     0       0.26597520 753   0_0  0.1329876  753 1
2 0     1       0.17964767 522   0_1  0.2228114 1275 2
3 0     2       0.16247703 480   0_2  0.3040499 1755 3
4 0     53      0.10094447 283   0_53 0.3545222 2038 4
5 0     4       0.08522127 246   0_4  0.3971328 2284 5
6 0     3       0.08504011 262   0_3  0.4396529 2546 6

In [22]:
curr.counts.norm = counts.norm[counts.norm$size>minCell,]
#tmp.thresh = curr.counts.norm %>% group_by(name) %>% summarize(size=sum(size))
#curr.counts.norm = curr.counts.norm[tmp.thresh$size > 1, ]

curr.counts.norm = curr.counts.norm[order(curr.counts.norm$name),]
topClones = unique(curr.counts.norm$name)
#curr.counts.norm

## Save

In [28]:
out.curr.counts.norm = tidyr::pivot_wider(curr.counts.norm, id_cols="name",values_from="norm", names_from="condition")
out.curr.counts.norm$size.mean = rowMeans(out.curr.counts.norm %>% dplyr::select(dplyr::all_of(sample_names)))

In [29]:

if(length(sample_names)==1){
    out.curr.counts.norm$fold = 1
}else{
    out.curr.counts.norm$fold =  out.curr.counts.norm[[sample_names[1]]]/out.curr.counts.norm[[sample_names[2]]]
    #out.curr.counts.norm = out.curr.counts.norm %>% arrange(desc(size.mean)) %>% dplyr::select(-c(size.mean))
    }
out.curr.counts.norm = out.curr.counts.norm %>% arrange(desc(fold))  %>% dplyr::select(-c(size.mean))
ord.inds = as.character(out.curr.counts.norm[["name"]])
out.curr.counts.norm

    name Control     Flt3l        Input        fold
1   1_24 0.021242485 0.0061079063 0.0299566417 3.477867
2   1_7  0.027655311 0.0091618595 0.0516357903 3.018526
3   1_5  0.036072144 0.0122158127 0.0441466299 2.952906
4   1_19 0.020440882 0.0071258907 0.0366574695 2.868537
5   1_14 0.025250501 0.0091618595 0.0374458021 2.756045
6   0_56 0.001532959 0.0006079027 0.0008789921 2.521717
7   1_6  0.027655311 0.0118764846 0.0500591250 2.328577
8   1_22 0.025250501 0.0108585002 0.0220733149 2.325413
9   1_48 0.004408818 0.0020359688 0.0094599921 2.165464
10  0_32 0.016862545 0.0097264438 0.0158218576 1.733680
11  1_42 0.006412826 0.0037326094 0.0197083169 1.718054
12  1_8  0.038877756 0.0227349847 0.0236499803 1.710041
13  0_50 0.001532959 0.0009118541 0.0038089657 1.681145
14  0_51 0.002043945 0.0012158055 0.0029299736 1.681145
15  0_10 0.022994379 0.0139817629 0.0307647231 1.644598
16  0_8  0.022994379 0.0139817629 0.0360386757 1.644598
17  0_7  0.034747062 0.0218844985 0.0219748022 1.587748
18  0_38 0.016862545 0.0106382979 0.0120128919 1.585079
19  1_43 0.009619238 0.0061079063 0.0165549862 1.574883
20  0_3  0.018395503 0.0118541033 0.0547905069 1.551826
21  1_46 0.005210421 0.0033932813 0.0082774931 1.535511
22  1_16 0.025250501 0.0166270784 0.0252266456 1.518637
23  0_44 0.008175779 0.0054711246 0.0087899209 1.494351
24  0_35 0.015840572 0.0106382979 0.0137708761 1.489014
25  0_29 0.019417476 0.0136778116 0.0125988866 1.419633
26  1_26 0.022845691 0.0162877503 0.0153724872 1.402630
27  1_1  0.035671343 0.0261282660 0.0563657864 1.365240
28  0_13 0.019928462 0.0148936170 0.0284207442 1.338054
29  1_20 0.025250501 0.0190023753 0.0173433189 1.328808
30  1_2  0.059719439 0.0454699695 0.0141899882 1.313382
⋮   ⋮    ⋮           ⋮            ⋮            ⋮
98  1_36 0.011623246 0.0183237190 0.0070949941 0.6343279
99  1_29 0.013226453 0.0230743129 0.0098541585 0.5732111
100 1_21 0.018036072 0.0356294537 0.0031533307 0.5062124
101 0_52 0.001532959 0.0030395137 0.0008789921 0.5043434
102 0_37 0.012263669 0.0264437690           NA 0.4637640
103 0_4  0.026060296 0.0562310030 0.0029299736 0.4634507
104 0_5  0.024016352 0.0544072948 0.0014649868 0.4414179
105 1_3  0.027254509 0.0675262979 0.0019708317 0.4036133
106 1_51 0.002404810 0.0074652189 0.0031533307 0.3221352
107 1_49 0.001603206 0.0115371564           NA 0.1389603
108 1_50 0.001202405 0.0098405158 0.0027591644 0.1221892
109 0_55 0.001532959           NA 0.0020509815        NA
110 0_57          NA 0.0009118541 0.0017579842        NA
111 0_58          NA 0.0012158055 0.0008789921        NA
112 0_59          NA 0.0006079027 0.0008789921        NA
113 0_60          NA           NA 0.0014649868        NA
114 0_61          NA 0.0006079027 0.0005859947        NA
115 0_62          NA           NA 0.0011719895        NA
116 0_63          NA           NA 0.0008789921        NA
117 0_64          NA           NA 0.0005859947        NA
118 0_65          NA           NA 0.0008789921        NA
119 0_66          NA           NA 0.0005859947        NA
120 0_67          NA           NA 0.0005859947        NA
121 0_68          NA           NA 0.0008789921        NA
122 0_70          NA           NA 0.0005859947        NA
123 0_71          NA           NA 0.0005859947        NA
124 0_72          NA           NA 0.0005859947        NA
125 0_73          NA           NA 0.0005859947        NA
126 1_52          NA 0.0037326094           NA        NA
127 1_53          NA 0.0016966407           NA        NA

In [31]:
out.curr.counts = tidyr::pivot_wider(curr.counts.norm, id_cols="name",values_from="size", names_from="condition")
out.curr.counts = as.data.frame(out.curr.counts)
row.names(out.curr.counts) = out.curr.counts$name
out.curr.counts = out.curr.counts[ord.inds,]
out.curr.counts

     name Control Flt3l Input
1_24 1_24  53      18    76
1_7  1_7   69      27   131
1_5  1_5   90      36   112
1_19 1_19  51      21    93
1_14 1_14  63      27    95
0_56 0_56   3       2     3
1_6  1_6   69      35   127
1_22 1_22  63      32    56
1_48 1_48  11       6    24
0_32 0_32  33      32    54
1_42 1_42  16      11    50
1_8  1_8   97      67    60
0_50 0_50   3       3    13
0_51 0_51   4       4    10
0_10 0_10  45      46   105
0_8  0_8   45      46   123
0_7  0_7   68      72    75
0_38 0_38  33      35    41
1_43 1_43  24      18    42
0_3  0_3   36      39   187
1_46 1_46  13      10    21
1_16 1_16  63      49    64
0_44 0_44  16      18    30
0_35 0_35  31      35    47
0_29 0_29  38      45    43
1_26 1_26  57      48    39
1_1  1_1   89      77   143
0_13 0_13  39      49    97
1_20 1_20  63      56    44
1_2  1_2  149     134    36
⋮    ⋮    ⋮       ⋮     ⋮
1_36 1_36 29       54   18
1_29 1_29 33       68   25
1_21 1_21 45      105    8
0_52 0_52  3       10    3
0_37 0_37 24       87   NA
0_4  0_4  51      185   10
0_5  0_5  47      179    5
1_3  1_3  68      199    5
1_51 1_51  6       22    8
1_49 1_49  4       34   NA
1_50 1_50  3       29    7
0_55 0_55  3       NA    7
0_57 0_57 NA        3    6
0_58 0_58 NA        4    3
0_59 0_59 NA        2    3
0_60 0_60 NA       NA    5
0_61 0_61 NA        2    2
0_62 0_62 NA       NA    4
0_63 0_63 NA       NA    3
0_64 0_64 NA       NA    2
0_65 0_65 NA       NA    3
0_66 0_66 NA       NA    2
0_67 0_67 NA       NA    2
0_68 0_68 NA       NA    3
0_70 0_70 NA       NA    2
0_71 0_71 NA       NA    2
0_72 0_72 NA       NA    2
0_73 0_73 NA       NA    2
1_52 1_52 NA       11   NA
1_53 1_53 NA        5   NA

In [32]:
readr::write_csv(out.curr.counts.norm, file.path(outdir, "clone_sizes_norm.csv"))
readr::write_csv(out.curr.counts, file.path(outdir, "clone_sizes.csv"))

In [ ]:
ggplot(data=curr.counts.norm, aes(x=name,y=norm, fill = condition)) + 
        geom_col(position='dodge') 
    

ggsave(file.path(outdir, "topClonesSize_NormBatch.pdf"))

Saving 6.67 x 6.67 in image

In [ ]:
ggplot(data=curr.counts.norm, aes(x=name,y=size, fill = condition)) + 
        geom_col(position='dodge') 
    

ggsave(file.path(outdir, "topClonesSize.pdf"))

In [ ]:
sessionInfo()